MVC_Project/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MVC.DataAccess;
using MVC.DataAccess.IRebository;
using MVC.Model;
using MVC.Utiltiy;
using System.Runtime.InteropServices;

namespace MVC_Project.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize (Roles =SD.Role_Admin)]
    public class CategoryController : Controller
    {
       
        private readonly IUnitOfWork _unitOfWork;
        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IActionResult> Index()
        {
            var result = await _unitOfWork.Category.GetAll();
            return View(result);
        }
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Category category)
        {
            if (ModelState.IsValid)
            {
                await _unitOfWork.Category.Insert(category);
                await _unitOfWork.Save();
                TempData["success"] = "Category Created Success";
                return RedirectToAction("Index");
            }
            return View();
        }
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            var result  =await _unitOfWork.Category.Get(q=>q.Id==id);
            if (result == null)
            {
                return NotFound();
            }
            return View(result);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Update(category);
                await _unitOfWork.Save();
                TempData["success"] = "Category Update Success";
                return RedirectToAction("Index");
            }
            return View();
        }
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            var result = await _unitOfWork.Category.Get(q => q.Id == id);
            if (result == null)
            {
                return NotFound();
            }
            return View(result);
        }
        [HttpPost, ActionName("Delete")]

        public async Task<IActionResult> DeletePost(int id)
        {
            var result = await _unitOfWork.Category.Get(q => q.Id == id);
            if (result == null)
            {
                return NotFound();
            }
            await _unitOfWork.Category.Delete(id);
            await _unitOfWork.Save();
            TempData["success"] = "Category Deleted Success";
            return RedirectToAction("Index");

        }
    }
}

MVC_Project/Areas/Admin/Controllers/ProductController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Routing;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using MVC.DataAccess.IRebository;
using MVC.Model;
using MVC.Model.DTOs;
using MVC.Model.VM;
using MVC.Utiltiy;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

namespace MVC_Project.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;
        private IWebHostEnvironment _environment;

        public ProductController(IUnitOfWork unitOfWork, IMapper mapper, IWebHostEnvironment environment)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
            _environment = environment;
        }

        public async Task<IActionResult> Index()
        {
            var result = await _unitOfWork.Product.GetAll(include:q=>q.Include(x=>x.Category));
            return View(result);
        }
        public async Task<IActionResult> Upsert(int? id)
        {
            ProductVM product = new();
            var CategoryList = await _unitOfWork.Category.GetAll();
            var result = _mapper.Map<IList<CategoryDTO>>(CategoryList);

            if (id == null || id == 0)
            {
                product.Categorys = result.Select(u => new SelectListItem { Text = u.Name, Value = u.Id.ToString() });
                product.Product = new ProductDTO();
                return View(product);
            }
            else
            {
                var productt = await _unitOfWork.Product.Get(q => q.Id == id);
                var results = _mapper.Map<ProductDTO>(productt);
                product.Categorys = result.Select(u => new SelectListItem { Text = u.Name, Value = u.Id.ToString() });
                product.Product = new ProductDTO();
                product.Product = results;
                productt.Used = true;
                _unitOfWork.Product.Update(productt);
                await _unitOfWork.Save(); 
                return View(product);
            }
            
        }
        [HttpPost]
        public async Task<IActionResult> Upsert(ProductDTO Product,IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                string rote = _environment.WebRootPath;
                if(file!=null)
                {
                    string fileName = Guid.NewGuid().ToString()+Path.GetExtension(file.FileName);
                    string productPath = Path.Combine(rote, @"images\product");
                    if(!string.IsNullOrEmpty(Product.ImageUrl))
                    {
                        var old = Path.Combine(rote, Product.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(old))
                        {
                            System.IO.File.Delete(old);
                        }
                    }

                    using (var FileStream =new FileStream(Path.Combine(productPath,fileName),FileMode.Create))
                    {
                        file.CopyTo(FileStream);
                    }
                    Product.ImageUrl = @"\images\product\" + fileName;
                }
                if (Product.Id != 0)
                {
                    var map = _mapper.Map<Product>(Product);
                    map.Used = false;
                    _unitOfWork.Product.Update(map);
                    await _unitOfWork.Save();
                    TempData["success"] = "Category Update Success";
                }
                else
                {
                    
                    var map = _mapper.Map<Product>(Product);
                    await _unitOfWork.Product.Insert(map);
                    await _unitOfWork.Save();
                    TempData["success"] = "Category Created Success";
                }
                return RedirectToAction("Index");
            }
            return View();
        }
       /* public async Task<IActionResult> Upload(int id,IFormFile? file)
        {

            string rote = _environment.WebRootPath;
            if (file != null)
            {
                string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                string productPath = Path.Combine(rote, @"images\product");
                var image = await _unitOfWork.Product.Get(q => q.Id == id);

                if (!string.IsNullOrEmpty(image.ImageUrl))
                {
                    var old = Path.Combine(rote, image.ImageUrl.TrimStart('\\'));
                    if (System.IO.File.Exists(old))
                    {
                        System.IO.File.Delete(old);
                    }
                }

                using (var FileStream = new FileStream(Path.Combine(productPath, fileName), FileMode.Create))
                {
                    file.CopyTo(FileStream);
                }
                image.ImageUrl = @"\images\product\" + fileName;
                image.Used = true;
                _unitOfWork.Product.Update(image);
                await _unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View();

        }*/
        public async Task<IActionResult> Download(int id)
        {
            string rote = _environment.WebRootPath;
            var image = await _unitOfWork.Product.Get(q => q.Id == id);
            var old = Path.Combine(rote, image.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(old))
            {
                MemoryStream stream = new MemoryStream();
                using (FileStream file = new FileStream(old, FileMode.Open)
                )
                {
                    await file.CopyToAsync(stream);
                }
                //stream.Position = 0;
                image.CurrentUserId = CurrentUserId.CurrentId;
                image.Used = true;
                _unitOfWork.Product.Update(image);
                await _unitOfWork.Save();
                return File(stream.ToArray(), "image/jpg", image.Title );
            }
            else { return NotFound(); }
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            var result = await _unitOfWork.Product.Get(q => q.Id == id);
            if (result == null)
            {
                return NotFound();
            }
            return View(result);
        }
        [HttpPost, ActionName("Delete")]

        public async Task<IActionResult> DeletePost(int id)
        {
            var result = await _unitOfWork.Product.Get(q => q.Id == id);
            if (result == null)
            {
                return NotFound();
            }
            if (!string.IsNullOrEmpty(result.ImageUrl))
            {
                var old = Path.Combine(_environment.WebRootPath, result.ImageUrl.TrimStart('\\'));
                if (System.IO.File.Exists(old))
                {
                    System.IO.File.Delete(old);
                }
            }
            await _unitOfWork.Product.Delete(id);
            await _unitOfWork.Save();
            TempData["success"] = "Category Deleted Success";
            return RedirectToAction("Index");

        }
    }
}

MVC_Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_Project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC_Project.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC_Project</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                       
                        <li class="nav-item">
                            <a class="nav-link text" asp-area="Customer" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if(User.IsInRole(SD.Role_Admin)){
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Content Managment
                            </a>
                           
                            <ul class="dropdown-menu">
                                <li class="nav-item">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                </li>
                                <li class="nav-item">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                </li>
                                <li><hr class="dropdown-divider"></li>
                                
                            </ul>
                        </li>
                        }
                    </ul>
                    <partial name="_LoginPartial"/>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notifications" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-primary text-muted">
        <div class="text-center">
            Made With <i class="bi bi-ev-front-fill"></i> by Yihea
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.tiny.cloud/1/ata2tffo5wto6wqs2q6n2xcofdfi45q3b7fb8sg9alanzb8d/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVC_Project/Views/Shared/_Notifications.cshtml
@if(TempData["success"]!=null){
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');</script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');</script>
}